CAR_BRANDS = {
    "Acura": ["CL", "Integra", "MDX", "NSX", "RDX", "RL", "RSX", "TL", "TSX", "ZDX"],
    "Alfa Romeo": ["145", "146", "147", "155", "156", "159", "164", "166", "4C", "8C", "Brera", "Giulia", "Giulietta", "GT", "GTV", "MiTo", "Spider", "Stelvio", "Tonale"],
    "Aston Martin": ["DB11", "DB9", "DBS", "Rapide", "Vantage", "Vanquish", "Virage", "Vulcan"],
    "Audi": ["100", "80", "A1", "A2", "A3", "A4", "A4 Allroad", "A5", "A6", "A6 Allroad", "A7", "A8", "e-tron", "e-tron GT", "Q2", "Q3", "Q4 e-tron", "Q5", "Q7", "Q8", "R8", "RS3", "RS4", "RS5", "RS6", "RS7", "RSQ3", "RSQ8", "S1", "S3", "S4", "S5", "S6", "S7", "S8", "SQ2", "SQ5", "SQ7", "SQ8", "TT", "TT RS"],
    "Bentley": ["Arnage", "Azure", "Bentayga", "Brooklands", "Continental", "Continental GT", "Flying Spur", "Mulsanne"],
    "BMW": ["1 Series", "1M", "2 Series", "2 Series Active Tourer", "2 Series Gran Tourer", "3 Series", "3 Series GT", "4 Series", "4 Series Gran Coupe", "5 Series", "5 Series GT", "6 Series", "6 Series GT", "7 Series", "8 Series", "i3", "i4", "i8", "iX", "iX3", "M2", "M3", "M4", "M5", "M6", "M8", "X1", "X2", "X3", "X4", "X5", "X5 M", "X6", "X6 M", "X7", "Z3", "Z4", "Z8"],
    "Cadillac": ["ATS", "BLS", "CTS", "DeVille", "DTS", "Escalade", "Seville", "SRX", "STS", "XLR", "XT5", "XTS"],
    "Chevrolet": ["Aveo", "Camaro", "Captiva", "Corvette", "Cruze", "Epica", "HHR", "Impala", "Kalos", "Lacetti", "Malibu", "Matiz", "Orlando", "Spark", "Suburban", "Tahoe", "Trax", "Volt"],
    "Chrysler": ["300C", "300M", "Crossfire", "Grand Voyager", "Neon", "Pacifica", "PT Cruiser", "Sebring", "Stratus", "Voyager"],
    "Citroen": ["2 CV", "AX", "Berlingo", "BX", "C-Crosser", "C-Elysee", "C-Zero", "C1", "C2", "C3", "C3 Aircross", "C3 Picasso", "C4", "C4 Aircross", "C4 Cactus", "C4 Picasso", "C4 SpaceTourer", "C5", "C5 Aircross", "C6", "C8", "DS3", "DS4", "DS5", "E-Mehari", "Grand C4 Picasso", "Jumper", "Jumpy", "Nemo", "Saxo", "Xantia", "XM", "Xsara", "Xsara Picasso", "ZX"],
    "Dacia": ["Dokker", "Duster", "Jogger", "Lodgy", "Logan", "Sandero", "Sandero Stepway", "Spring"],
    "Daewoo": ["Espero", "Kalos", "Lacetti", "Lanos", "Leganza", "Matiz", "Nexia", "Nubira", "Tacuma", "Tico"],
    "Daihatsu": ["Charade", "Copen", "Cuore", "Feroza", "Materia", "Rocky", "Sirion", "Terios", "Trevis", "YRV"],
    "Dodge": ["Avenger", "Caliber", "Challenger", "Charger", "Dakota", "Dart", "Durango", "Journey", "Magnum", "Nitro", "RAM", "Viper"],
    "Ferrari": ["296 GTB", "360", "458", "488", "599 GTB", "812 Superfast", "California", "F12berlinetta", "F430", "F8 Tributo", "FF", "GTC4Lusso", "LaFerrari", "Portofino", "Roma", "SF90 Stradale"],
    "Fiat": ["124 Spider", "500", "500L", "500X", "Barchetta", "Brava", "Bravo", "Cinquecento", "Coupe", "Croma", "Doblo", "Ducato", "Fiorino", "Freemont", "Fullback", "Grande Punto", "Idea", "Linea", "Marea", "Multipla", "Palio", "Panda", "Punto", "Punto Evo", "Qubo", "Scudo", "Sedici", "Seicento", "Stilo", "Talento", "Tipo", "Ulysse", "Uno"],
    "Ford": ["B-Max", "C-Max", "Cougar", "EcoSport", "Edge", "Escort", "Explorer", "F-150", "Fiesta", "Focus", "Fusion", "Galaxy", "Grand C-Max", "Ka", "Ka+", "Kuga", "Maverick", "Mondeo", "Mustang", "Mustang Mach-E", "Orion", "Puma", "Ranger", "S-Max", "Scorpio", "Sierra", "Streetka", "Tourneo Connect", "Tourneo Courier", "Tourneo Custom", "Transit", "Transit Connect", "Transit Courier", "Transit Custom"],
    "Great Wall": ["C30", "H6", "Hover", "Steed", "Voleex C10"],
    "Honda": ["Accord", "City", "Civic", "CR-V", "CR-X", "CR-Z", "e", "FR-V", "HR-V", "Insight", "Integra", "Jazz", "Legend", "Logo", "NSX", "Odyssey", "Pilot", "Prelude", "S2000", "Shuttle", "Stream"],
    "Hummer": ["H1", "H2", "H3"],
    "Hyundai": ["Accent", "Atos", "Bayon", "Coupe", "Elantra", "Galloper", "Genesis", "Getz", "Grand Santa Fe", "H-1", "i10", "i20", "i30", "i40", "Ioniq", "Ioniq 5", "ix20", "ix35", "ix55", "Kona", "Lantra", "Matrix", "Santa Fe", "Sonata", "Terracan", "Trajet", "Tucson", "Veloster"],
    "Infiniti": ["EX", "FX", "G", "JX", "M", "Q30", "Q50", "Q60", "Q70", "QX30", "QX50", "QX56", "QX60", "QX70", "QX80"],
    "Isuzu": ["D-Max", "Trooper"],
    "Jaguar": ["E-Pace", "F-Pace", "F-Type", "I-Pace", "S-Type", "X-Type", "XE", "XF", "XJ", "XJ220", "XK", "XK8"],
    "Jeep": ["Cherokee", "Commander", "Compass", "Gladiator", "Grand Cherokee", "Patriot", "Renegade", "Wrangler"],
    "Kia": ["Carens", "Carnival", "Ceed", "Ceed SW", "Cerato", "EV6", "Magentis", "Niro", "Optima", "Picanto", "ProCeed", "Rio", "Sephia", "Shuma", "Sorento", "Soul", "Sportage", "Stinger", "Stonic", "Venga", "Xceed"],
    "Lada": ["110", "111", "112", "Granta", "Kalina", "Niva", "Priora", "Samara", "Vesta", "XRAY"],
    "Lamborghini": ["Aventador", "Countach", "Diablo", "Gallardo", "Huracan", "Murcielago", "Urus"],
    "Lancia": ["Dedra", "Delta", "Kappa", "Lybra", "Musa", "Phedra", "Thema", "Thesis", "Voyager", "Ypsilon", "Zeta"],
    "Land Rover": ["Defender", "Discovery", "Discovery Sport", "Freelander", "Range Rover", "Range Rover Evoque", "Range Rover Sport", "Range Rover Velar"],
    "Lexus": ["CT", "ES", "GS", "GX", "IS", "LC", "LS", "LX", "NX", "RC", "RX", "SC", "UX"],
    "Maserati": ["3200 GT", "Coupe", "Ghibli", "GranCabrio", "GranTurismo", "Levante", "MC20", "Quattroporte", "Spyder"],
    "Mazda": ["121", "2", "3", "323", "5", "6", "626", "BT-50", "CX-3", "CX-30", "CX-5", "CX-7", "CX-9", "Demio", "MPV", "MX-3", "MX-30", "MX-5", "MX-6", "Premacy", "RX-7", "RX-8", "Tribute", "Xedos"],
    "McLaren": ["540C", "570GT", "570S", "600LT", "650S", "675LT", "720S", "Artura", "GT", "MP4-12C", "P1"],
    "Mercedes-Benz": ["A-Class", "AMG GT", "B-Class", "C-Class", "Citan", "CL-Class", "CLA-Class", "CLC-Class", "CLK-Class", "CLS-Class", "E-Class", "EQA", "EQB", "EQC", "EQE", "EQS", "G-Class", "GL-Class", "GLA-Class", "GLB-Class", "GLC-Class", "GLE-Class", "GLK-Class", "GLS-Class", "M-Class", "R-Class", "S-Class", "SL-Class", "SLC-Class", "SLK-Class", "SLR McLaren", "SLS AMG", "V-Class", "Vaneo", "Viano", "Vito", "X-Class"],
    "Mini": ["Clubman", "Convertible", "Cooper", "Countryman", "Coupe", "One", "Paceman", "Roadster"],
    "Mitsubishi": ["3000 GT", "ASX", "Carisma", "Colt", "Eclipse", "Eclipse Cross", "Galant", "Grandis", "L200", "Lancer", "Lancer Evolution", "Outlander", "Pajero", "Pajero Pinin", "Pajero Sport", "Space Star", "Space Wagon"],
    "Nissan": ["350Z", "370Z", "Almera", "Almera Tino", "Ariya", "GT-R", "Juke", "Leaf", "Maxima", "Micra", "Murano", "Navara", "Note", "NV200", "Pathfinder", "Patrol", "Pixo", "Primera", "Pulsar", "Qashqai", "Qashqai+2", "Terrano", "Tiida", "X-Trail"],
    "Opel": ["Adam", "Agila", "Ampera", "Antara", "Astra", "Calibra", "Cascada", "Combo", "Corsa", "Crossland X", "Frontera", "Grandland X", "Insignia", "Kadett", "Karl", "Meriva", "Mokka", "Mokka X", "Monterey", "Movano", "Omega", "Signum", "Tigra", "Vectra", "Vivaro", "Zafira", "Zafira Life"],
    "Peugeot": ["1007", "106", "107", "108", "2008", "205", "206", "207", "208", "3008", "301", "306", "307", "308", "309", "4007", "4008", "405", "406", "407", "5008", "508", "605", "607", "806", "807", "Bipper", "Boxer", "Expert", "iOn", "Partner", "RCZ", "Rifter", "Traveller"],
    "Porsche": ["718 Boxster", "718 Cayman", "911", "918 Spyder", "Boxster", "Carrera GT", "Cayenne", "Cayman", "Macan", "Panamera", "Taycan"],
    "Renault": ["Arkana", "Austral", "Captur", "Clio", "Espace", "Fluence", "Grand Espace", "Grand Scenic", "Kadjar", "Kangoo", "Koleos", "Laguna", "Latitude", "Master", "Megane", "Modus", "Scenic", "Talisman", "Twingo", "Twizy", "Vel Satis", "Wind", "Zoe"],
    "Rolls-Royce": ["Cullinan", "Dawn", "Ghost", "Phantom", "Wraith"],
    "Rover": ["200", "25", "400", "45", "600", "75", "Mini", "Streetwise"],
    "Saab": ["9-3", "9-5", "900", "9000"],
    "Seat": ["Alhambra", "Altea", "Altea XL", "Arona", "Ateca", "Cordoba", "Exeo", "Ibiza", "Leon", "Mii", "Tarraco", "Toledo"],
    "Skoda": ["Citigo", "Enyaq iV", "Fabia", "Favorit", "Felicia", "Kamiq", "Karoq", "Kodiaq", "Octavia", "Rapid", "Roomster", "Scala", "Superb", "Yeti"],
    "Smart": ["Forfour", "Fortwo", "Roadster"],
    "SsangYong": ["Actyon", "Korando", "Kyron", "Musso", "Rexton", "Rodius", "Tivoli", "XLV"],
    "Subaru": ["BRZ", "Forester", "Impreza", "Justy", "Legacy", "Levorg", "Outback", "Solterra", "Tribeca", "WRX STI", "XV"],
    "Suzuki": ["Alto", "Baleno", "Celerio", "Grand Vitara", "Ignis", "Jimny", "Kizashi", "Liana", "Samurai", "Splash", "Swift", "SX4", "SX4 S-Cross", "Vitara", "Wagon R+"],
    "Tesla": ["Model 3", "Model S", "Model X", "Model Y", "Roadster"],
    "Toyota": ["Auris", "Avensis", "Avensis Verso", "Aygo", "Aygo X", "bZ4X", "C-HR", "Camry", "Celica", "Corolla", "Corolla Verso", "GT86", "Highlander", "Hilux", "IQ", "Land Cruiser", "Mirai", "MR2", "Previa", "Prius", "Prius+", "Proace", "RAV4", "Supra", "Urban Cruiser", "Verso", "Verso-S", "Yaris", "Yaris Cross"],
    "Volkswagen": ["Amarok", "Arteon", "Beetle", "Bora", "Caddy", "CC", "Corrado", "Crafter", "Eos", "Fox", "Golf", "Golf Plus", "Golf Sportsvan", "ID.3", "ID.4", "ID.5", "ID.Buzz", "Jetta", "Lupo", "Multivan", "New Beetle", "Passat", "Passat CC", "Phaeton", "Polo", "Scirocco", "Sharan", "T-Cross", "T-Roc", "Taigo", "Tiguan", "Tiguan Allspace", "Touareg", "Touran", "Transporter", "Up!"],
    "Volvo": ["C30", "C40", "C70", "S40", "S60", "S80", "S90", "V40", "V50", "V60", "V70", "V90", "XC40", "XC60", "XC70", "XC90"]
}