"""Add mileage, engine_size, transmission, color, doors, condition

Revision ID: 8fa9bb487264
Revises: 
Create Date: 2025-12-02 23:16:45.547000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fa9bb487264'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mileage', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('engine_size', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('transmission', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('color', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('euro_standard', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('doors', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('condition', sa.String(length=20), nullable=False))
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('horsepower',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('fuel',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.alter_column('fuel',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('horsepower',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('model',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('condition')
        batch_op.drop_column('doors')
        batch_op.drop_column('euro_standard')
        batch_op.drop_column('color')
        batch_op.drop_column('transmission')
        batch_op.drop_column('engine_size')
        batch_op.drop_column('mileage')

    # ### end Alembic commands ###
